[package]
name = "ghui-util"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
dotenv = "0.15.0"
github-graphql = { path = "../github-graphql" }
serde = "1.0.219"
serde_json = "*"
