// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountReadiness =
  | "ready"
  | "unverified"
  | "missingProjectScope"
  | "noProjectAccess"
  | "offline"
  | "timeout"
  | "invalidCredential"
  | "credentialMismatch"
  | "tokenMissing"
  | "environmentOnly"
  | "error";
