// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountListState } from "./AccountListState";
import type { GitHubAccount } from "./GitHubAccount";

export type AccountList = {
  state: AccountListState;
  accounts: Array<GitHubAccount>;
  message: string | null;
};
