// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedAccount } from "./SelectedAccount";

export type AccountState = {
  selected: SelectedAccount | null;
  busy: boolean;
  pendingEdits: number;
  accountGeneration: number;
};
