// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PivotField } from "./PivotField";

export type Axis =
  | { "kind": "pivot"; "field": PivotField }
  | { "kind": "group"; "field": PivotField }
  | { "kind": "hierarchy" }
  | { "kind": "sort"; "field": PivotField };
