// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";
import type { WorkItemId } from "./WorkItemId";

export type ChangeData =
  | { "type": "issueType"; "value": string | null }
  | { "type": "status"; "value": FieldOptionId | null }
  | { "type": "blocked"; "value": FieldOptionId | null }
  | { "type": "epic"; "value": FieldOptionId | null }
  | { "type": "iteration"; "value": FieldOptionId | null }
  | { "type": "kind"; "value": FieldOptionId | null }
  | { "type": "estimate"; "value": FieldOptionId | null }
  | { "type": "priority"; "value": FieldOptionId | null }
  | { "type": "setParent"; "value": WorkItemId }
  | { "type": "addToProject" };
