// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkItemId } from "./WorkItemId";

export type ChangeData =
  | { "type": "status"; "value": string | null }
  | { "type": "blocked"; "value": string | null }
  | { "type": "epic"; "value": string | null }
  | { "type": "setParent"; "value": WorkItemId }
  | { "type": "addToProject" };
