// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeData } from "./ChangeData";
import type { WorkItemId } from "./WorkItemId";

export type Change = { workItemId: WorkItemId; data: ChangeData };
