// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Changes } from "./Changes";
import type { Fields } from "./Fields";
import type { Filters } from "./Filters";
import type { Node } from "./Node";
import type { SanitizeConflict } from "./SanitizeConflict";
import type { WorkItem } from "./WorkItem";
import type { WorkItemId } from "./WorkItemId";

export type Data = {
  fields: Fields;
  workItems: { [key in WorkItemId]?: WorkItem };
  nodes: Array<Node>;
  originalWorkItems: { [key in WorkItemId]?: WorkItem };
  filters: Filters;
  changes: Changes;
  canUndo: boolean;
  canRedo: boolean;
  /**
   * Epic conflicts found during the last sanitize run.  Each entry
   * represents an item whose existing Epic was not overwritten; the user
   * can review these and selectively stage the override.
   */
  epicConflicts: Array<SanitizeConflict>;
};
