// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Data } from "./Data";
import type { WorkItem } from "./WorkItem";

export type DataUpdate =
  | { "type": "progress"; "value": { done: number; total: number } }
  | { "type": "workItem"; "value": WorkItem }
  | { "type": "data"; "value": Data };
