// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Changes } from "./Changes";
import type { Filters } from "./Filters";
import type { Node } from "./Node";
import type { WorkItem } from "./WorkItem";
import type { WorkItemId } from "./WorkItemId";

export type Data = {
  workItems: { [key in WorkItemId]?: WorkItem };
  nodes: Array<Node>;
  originalWorkItems: { [key in WorkItemId]?: WorkItem };
  filters: Filters;
  changes: Changes;
};
