// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";
import type { FieldOption } from "./FieldOption";
import type { FieldType } from "./FieldType";

export type Field = {
  id: FieldId;
  name: string;
  field_type: FieldType;
  options: Array<FieldOption>;
};
