// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";
import type { Iteration } from "./Iteration";
import type { SingleSelect } from "./SingleSelect";

export type Fields = {
  projectId: string;
  status: Field<SingleSelect>;
  blocked: Field<SingleSelect>;
  epic: Field<SingleSelect>;
  iteration: Field<Iteration>;
  kind: Field<SingleSelect>;
  workstream: Field<SingleSelect>;
  estimate: Field<SingleSelect>;
  priority: Field<SingleSelect>;
};
