// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";
import type { FieldOption } from "./FieldOption";

export type Field<T> = {
  id: FieldId;
  name: string;
  options: Array<FieldOption<T>>;
};
