// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";

export type Fields = {
  project_id: string;
  status: Field;
  blocked: Field;
  epic: Field;
  iteration: Field;
  project_milestone: Field;
  kind: Field;
};
