// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";

export type Filters = {
  status: Array<FieldOptionId | null>;
  blocked: Array<FieldOptionId | null>;
  epic: Array<FieldOptionId | null>;
  iteration: Array<FieldOptionId | null>;
  kind: Array<FieldOptionId | null>;
  workstream: Array<FieldOptionId | null>;
  estimate: Array<FieldOptionId | null>;
  priority: Array<FieldOptionId | null>;
  /**
   * Logins of assignees to filter out. `None` represents unassigned items.
   * An item is excluded when any of its assignees appears in this list, or
   * when it has no assignees and `None` is present.
   *
   * `#[serde(default)]` keeps existing cached `view_config.ghui.json` files
   * (which predate this field) deserializable.
   */
  assignee: Array<string | null>;
  /**
   * When true, items whose underlying GitHub state is closed (issues in
   * `CLOSED` state, pull requests in `CLOSED` or `MERGED` state) are
   * filtered out before bucketing. Items whose state hasn't loaded yet are
   * kept visible so we don't drop them based on unknown data.
   *
   * `#[serde(default)]` keeps existing cached `view_config.ghui.json`
   * files (which predate this field) deserializable.
   */
  hideClosed: boolean;
};
