// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";

export type Filters = {
  status: Array<FieldOptionId | null>;
  blocked: Array<FieldOptionId | null>;
  epic: Array<FieldOptionId | null>;
  iteration: Array<FieldOptionId | null>;
  kind: Array<FieldOptionId | null>;
  workstream: Array<FieldOptionId | null>;
  estimate: Array<FieldOptionId | null>;
  priority: Array<FieldOptionId | null>;
  /**
   * Exclusion list of assignee login names. Unlike the other fields above,
   * assignees are free-form GitHub logins (a work item may have several)
   * rather than project single-select option ids, so this is a list of
   * `String` logins. `None` represents items with no assignees. An item is
   * hidden when any of its assignees (or its unassigned state) appears here.
   *
   * `#[serde(default)]` keeps existing cached `view_config.ghui.json` files
   * (which predate this field) deserializable.
   */
  assignee: Array<string | null>;
  /**
   * When true, items whose underlying GitHub state is closed (issues in
   * `CLOSED` state, pull requests in `CLOSED` or `MERGED` state) are
   * filtered out before bucketing. Items whose state hasn't loaded yet are
   * kept visible so we don't drop them based on unknown data.
   *
   * `#[serde(default)]` keeps existing cached `view_config.ghui.json`
   * files (which predate this field) deserializable.
   */
  hideClosed: boolean;
};
