// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";

export type Filters = {
  status: Array<FieldOptionId | null>;
  blocked: Array<FieldOptionId | null>;
  epic: Array<FieldOptionId | null>;
  iteration: Array<FieldOptionId | null>;
  kind: Array<FieldOptionId | null>;
  workstream: Array<FieldOptionId | null>;
  estimate: Array<FieldOptionId | null>;
  priority: Array<FieldOptionId | null>;
  /**
   * When true, hide closed work items from the tree. The hierarchical
   * visibility logic in `NodeBuilder::should_include` still applies, so a
   * closed ancestor remains visible if it has any descendant that is not
   * hidden by this filter.
   */
  hideClosed: boolean;
};
