// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountReadiness } from "./AccountReadiness";
import type { AccountSource } from "./AccountSource";
import type { GitHubIdentity } from "./GitHubIdentity";

export type GitHubAccount = {
  identity: GitHubIdentity;
  avatarUri: string | null;
  source: AccountSource;
  readiness: AccountReadiness;
  selected: boolean;
  selectable: boolean;
  detail: string | null;
};
