// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueState } from "./IssueState";
import type { WorkItemId } from "./WorkItemId";

export type Issue = { state: IssueState, subIssues: Array<WorkItemId>, trackedIssues: Array<WorkItemId>, };
