// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkItemId } from "./WorkItemId";

export type ItemToUpdate = { workItemId: WorkItemId; force: boolean };
