// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

export type LogEntry = { timestamp: string; level: LogLevel; message: string };
