// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeData } from "./NodeData";

export type Node = { level: number, id: string, data: NodeData, hasChildren: boolean, };
