// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";

export type NodeData = { "type": "workItem" } | {
  "type": "group";
  name: string;
  fieldOptionId: FieldOptionId | null;
};
