// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";
import type { WorkItemId } from "./WorkItemId";

export type NodeData = { "type": "workItem"; workItemId: WorkItemId } | {
  "type": "group";
  name: string;
  fieldOptionId: FieldOptionId | null;
};
