// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PivotField =
  | "status"
  | "blocked"
  | "epic"
  | "iteration"
  | "kind"
  | "workstream"
  | "estimate"
  | "priority"
  | "assignee"
  | "repository"
  | "issueType"
  | "type"
  | "state";
