// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { MultiValueStrategy } from "./MultiValueStrategy";

export type PivotConfig = {
  recipe: Array<Axis>;
  multiValueStrategy: MultiValueStrategy;
  showGhostAncestors: boolean;
};
