// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelayLoad } from "./DelayLoad";
import type { FieldOptionId } from "./FieldOptionId";
import type { ProjectItemId } from "./ProjectItemId";

export type ProjectItem = {
  id: ProjectItemId;
  updatedAt: string;
  status: DelayLoad<FieldOptionId | null>;
  iteration: DelayLoad<FieldOptionId | null>;
  blocked: DelayLoad<FieldOptionId | null>;
  kind: DelayLoad<FieldOptionId | null>;
  epic: DelayLoad<FieldOptionId | null>;
  workstream: DelayLoad<FieldOptionId | null>;
  projectMilestone: DelayLoad<FieldOptionId | null>;
};
