// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelayLoad } from "./DelayLoad";
import type { IterationFieldValue } from "./IterationFieldValue";
import type { ProjectItemId } from "./ProjectItemId";
import type { SingleSelectFieldValue } from "./SingleSelectFieldValue";

export type ProjectItem = {
  id: ProjectItemId;
  updatedAt: string;
  status: DelayLoad<SingleSelectFieldValue | null>;
  iteration: DelayLoad<IterationFieldValue | null>;
  blocked: DelayLoad<SingleSelectFieldValue | null>;
  kind: DelayLoad<SingleSelectFieldValue | null>;
  epic: DelayLoad<SingleSelectFieldValue | null>;
  workstream: DelayLoad<SingleSelectFieldValue | null>;
  projectMilestone: DelayLoad<SingleSelectFieldValue | null>;
};
