// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an available update.
 */
export type ReleaseInfo = {
  /**
   * The release tag, e.g. `"v0.2.0"`.
   */
  tagName: string;
  /**
   * The direct download URL for the NSIS installer exe.
   */
  downloadUrl: string;
};
