// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkItemId } from "./WorkItemId";

/**
 * The result of resolving a GitHub URL to a project item identifier.
 *
 * The frontend uses this to determine whether the item is already in the
 * project (by checking `id` against `data.workItems`) and to retrieve the
 * current parent (if any) to decide whether a reparent confirmation dialog is
 * needed before staging a `SetParent` change.
 */
export type ResolvedUrl = {
  /**
   * The GitHub global node ID of the resolved issue.
   */
  id: WorkItemId;
  /**
   * The title of the resolved issue.
   */
  title: string;
};
