// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldOptionId } from "./FieldOptionId";
import type { WorkItemId } from "./WorkItemId";

/**
 * A single Epic conflict found during sanitize: the item already has an Epic
 * set, but the hierarchy says it should inherit a different one.
 */
export type SanitizeConflict = {
  workItemId: WorkItemId;
  /**
   * The Epic currently set on the item.
   */
  currentEpic: FieldOptionId;
  /**
   * The Epic the hierarchy says this item should have.
   */
  proposedEpic: FieldOptionId;
};
