// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountState } from "./AccountState";

export type SelectAccountResult =
  | { "type": "selected"; state: AccountState }
  | { "type": "confirmationRequired"; pendingEdits: number };
