// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubIdentity } from "./GitHubIdentity";
import type { SelectedAccountState } from "./SelectedAccountState";

export type SelectedAccount = {
  identity: GitHubIdentity;
  avatarUri: string;
  state: SelectedAccountState;
};
