// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All telemetry events the app can record.  Each variant carries only the data
 * relevant to that event.  Serialization to JSON happens inside [`record()`],
 * keeping the rest of the codebase free of raw `serde_json::Value`.
 */
export type TelemetryEvent =
  | { "event": "session_start" }
  | { "event": "refresh" }
  | {
    "event": "save";
    changes_count: number;
    duration_ms: bigint;
    success: boolean;
  }
  | { "event": "discard"; changes_count: number }
  | { "event": "preview_toggled"; enabled: boolean }
  | { "event": "filter_changed"; active_filters: number }
  | { "event": "field_changed"; field: string; value: string | null }
  | { "event": "change_reverted"; field: string; value: string | null }
  | { "event": "undo" }
  | { "event": "redo" }
  | { "event": "sanitize"; changes_count: number }
  | { "event": "convert_tracked" }
  | { "event": "add_item_from_url"; has_parent: boolean }
  | { "event": "mode_switched"; to: string }
  | { "event": "log_panel_toggled"; open: boolean }
  | { "event": "pending_changes_opened" }
  | { "event": "find_dialog" }
  | { "event": "column_reorder"; column: string }
  | { "event": "column_resize"; column: string }
  | { "event": "expand_collapse"; action: string };
