// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectItem } from "./ProjectItem";
import type { WorkItemData } from "./WorkItemData";
import type { WorkItemId } from "./WorkItemId";

export type WorkItem = {
  id: WorkItemId;
  title: string;
  updatedAt: string | null;
  resourcePath: string | null;
  repository: string | null;
  data: WorkItemData;
  projectItem: ProjectItem;
};
