// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubIdentity } from "./GitHubIdentity";

export type WorkItemsExtraData = { identity: GitHubIdentity; data: string };
